name: Publish contents

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Prepare SSH key
        env:
          ID_ED25519: ${{ secrets.ID_ED25519 }}
        run: |
          mkdir -p ~/.ssh
          echo "$ID_ED25519\n" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        shell: bash

      - name: Deploy
        env:
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_USER: ${{ vars.SSH_USER }}
          SSH_PATH: ${{ vars.SSH_PATH }}
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
        run: |
          echo "Deploying..."

          for i in {1..5}; do
            rsync -avz \
              -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
              .vitepress/dist/ $SSH_USER@$SSH_HOST:$SSH_PATH
            if [ $? -eq 0 ]; then
              break
            fi
            sleep 5
          done

          rm -f ~/.ssh/id_ed25519
        shell: bash
